### ISSUE TITLE
SVG向下兼容

### ISSUE THREAD

**Issue by ljwrer** [ljwrer/tricks#3]
[http://www.zhangxinxu.com/wordpress/2013/09/svg-fallbacks/](url)
## svg hack
```css
.my-element {
  background-image: url(fallback.png);
  background-image: url(image.svg), none;
}
```
